name: Release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup update
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain stable
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Build release Win
      if: runner.os == 'Windows'
      run: cargo build --release

    - name: Build release Unix
      if: runner.os != 'Windows'
      run: cargo build --release
      env:
        RUSTFLAGS: '-C link-arg=-s'

    - name: Pack Unix
      if: runner.os != 'Windows'
      run: zip -j gcloud-reader-${{runner.os}}.zip target/release/gcloud-reader

    - name: Pack Windows
      if: runner.os == 'Windows'
      run: Compress-Archive -Path target/release/gcloud-reader.exe -Destination gcloud-reader-${{runner.os}}.zip

    - name: Upload to release Unix
      if: runner.os != 'Windows'
      run: |
        curl \
          -f \
          -sSL \
          -XPOST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --upload-file "gcloud-reader-${{runner.os}}.zip" \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=gcloud-reader-${{runner.os}}.zip"

    - name: Upload to release Windows
      if: runner.os == 'Windows'
      run: |
        $headers = @{"Authorization"="token ${{ secrets.GITHUB_TOKEN }}" };
        $event = Get-Content -Raw -Path $env:GITHUB_EVENT_PATH | ConvertFrom-Json;
        $url = "https://uploads.github.com/repos/$($env:GITHUB_REPOSITORY)/releases/$($event.release.id)/assets?name=gcloud-reader-${{runner.os}}.zip";
        Invoke-WebRequest -Headers $headers -Method POST -Infile gcloud-reader-${{runner.os}}.zip -ContentType 'application/zip' -Uri $url

  build-apple-aarch64:
    runs-on: macos-latest

    strategy:
      matrix:
        target: [aarch64-apple-darwin]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Rust version
      run: |
        cargo --version
        rustc --version
    - name: Available SDK
      run: xcodebuild -showsdks

    - name: Install rust target
      run: rustup target add ${{matrix.target}}

    - name: Build release
      run: SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)  cargo build --release --target ${{matrix.target}}
      env:
        RUSTFLAGS: '-C link-arg=-s'

    - name: Pack
      run: zip -j gcloud-reader-${{matrix.target}}.zip target/${{matrix.target}}/release/gcloud-reader

    - name: Upload to release Unix
      run: |
        curl \
          -f \
          -sSL \
          -XPOST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --upload-file "gcloud-reader-${{matrix.target}}.zip" \
          "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=gcloud-reader-${{matrix.target}}.zip"
